PLGN-199 ArgumentCountError: Too few arguments to function WC_Data_Exception::__construct(), 1 passed in (#122) (#124)
* add argument into the translation function

* remove 400 status code and add cardknox_declined

(cherry picked from commit 150a422b5c2687289bed60bf97d53bc559a38d5a)

Co-authored-by: Pritesh Modi <pritesh.lr@gmail.com>